main: me.kate.genbuckets.Main
name: RuthlessGenBucket
version: 1.0
api-version: 1.13
author: Biscut, Kate
depend: [Vault]
softdepend: [MassiveCore, CoreProtect, Factions, WorldGuard, WorldBorder]
commands:
  genbucket:
    description: Opens the genbucket shop.
    aliases: [gb, gen, bucket, genbucketshop, bucketshop]
  genbucketadmin:
    description: The main command for admin/console bucket tools.
    aliases: [gba]
permissions:
  genbucket.admin:
    children:
      genbucket.give: true
      genbucket.reload: true
      genbucket.bypass: true
  genbucket.give:
    default: op
  genbucket.reload:
    default: op
  genbucket.bypass:
    default: op
  genbucket.shop:
    default: true
  genbucket.use:
    default: true