main: codes.biscuit.simplegenbuckets.SimpleGenBuckets
name: SimpleGenBuckets
version: ${version}
api-version: 1.13
author: Biscut
depend: [Vault]
commands:
  genbucket:
    description: Opens the genbucket shop.
    aliases: [gb, bucket, genbucketshop, bucketshop]
  genbucketadmin:
    description: The main command for admin/console tools.
    aliases: [gba]
permissions:
  simplegenbuckets.admin:
    children:
      simplegenbuckets.give: true
      simplegenbuckets.reload: true
      simplegenbuckets.bypass: true
  simplegenbuckets.give:
    default: op
  simplegenbuckets.reload:
    default: op
  simplegenbuckets.bypass:
    default: op
  simplegenbuckets.shop:
    default: true
  simplegenbuckets.use:
    default: true